name: Auto Backup

on:
  # 매일 자정에 실행
  schedule:
    - cron: '0 0 * * *'
  
  # 파일 변경이 있을 때마다 실행 (선택 사항)
  push:
    branches: [ main ]
  
  # 수동 실행 트리거 추가
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up job
        run: echo "Starting auto backup job"
      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      
      - name: Commit and push changes
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto backup - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
