name: Auto Backup

on:
  # 매일 자정에 실행
  schedule:
    - cron: '0 0 * * *'
  
  # 파일 변경이 있을 때마다 실행 (선택 사항)
  push:
    branches: [ main ]
  
  # 수동 실행 트리거 추가
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    # 워크플로우에 쓰기 권한 부여
    permissions:
      contents: write
    
    steps:
      - name: Set up job
        run: echo "Starting auto backup job"
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # 전체 히스토리 가져오기 (기본값은 1)
          fetch-depth: 0
      
      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      
      - name: Commit and push changes
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto backup - $(date +'%Y-%m-%d %H:%M:%S')"
          # GitHub 토큰을 사용하여 인증
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
