name: Auto Backup

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시가 있을 때 자동으로 실행됩니다.

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "keemsune"
          git config --global user.email "keemsune327@gmail.com"
      
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Auto backup"
          git push origin main
